import dotenv from "dotenv";import path from "node:path";import {fileURLToPath} from "node:url";import fs from "node:fs";
const here=path.dirname(fileURLToPath(import.meta.url));
dotenv.config({path:path.resolve(here,"../.env")});
dotenv.config({path:path.resolve(here,"../../.env")});
dotenv.config();
import express from "express";import cors from "cors";import multer from "multer";import Database from "better-sqlite3";import OpenAI from "openai";import crypto from "node:crypto";
const app=express();app.use(cors());app.use(express.json());const port=Number(process.env.PORT||4000);
let latestHardwareWeightKg:number|null=null;
let latestHardwareAt:string|null=null;
const deviceToken=()=>process.env.PI_DEVICE_TOKEN?.trim()||"";
fs.mkdirSync(path.resolve(here,"../data"),{recursive:true});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024}});const db=new Database(path.resolve(here,"../data/platescan.sqlite"));db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,session_date TEXT NOT NULL,day_label TEXT NOT NULL,round_number INTEGER NOT NULL,session_type TEXT NOT NULL DEFAULT 'round',meal_type TEXT NOT NULL DEFAULT 'Lunch',started_at TEXT NOT NULL,finished_at TEXT);CREATE TABLE IF NOT EXISTS plates(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,sequence INTEGER NOT NULL,captured_at TEXT NOT NULL,image_name TEXT,FOREIGN KEY(session_id) REFERENCES sessions(id));CREATE TABLE IF NOT EXISTS food_observations(id INTEGER PRIMARY KEY AUTOINCREMENT,plate_id TEXT NOT NULL,name TEXT NOT NULL,remaining_amount TEXT NOT NULL,remaining_percent INTEGER,estimated_count REAL,unit TEXT NOT NULL DEFAULT 'unit',confidence REAL NOT NULL,emoji TEXT NOT NULL,FOREIGN KEY(plate_id) REFERENCES plates(id));CREATE TABLE IF NOT EXISTS food_targets(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,food_name TEXT NOT NULL,prepared_quantity_kg REAL,serving_quantity_kg REAL,FOREIGN KEY(session_id) REFERENCES sessions(id));`);
try { db.prepare("ALTER TABLE sessions ADD COLUMN meal_type TEXT NOT NULL DEFAULT 'Lunch'").run(); } catch {}
function getClient(){const key=process.env.NABH_API_KEY?.trim();if(!key)throw new Error("NABH_API_KEY is missing. Put it in backend/.env and restart npm run dev.");return new OpenAI({apiKey:key,baseURL:process.env.NABH_BASE_URL||"https://api.nabh.cloud/v1"});}
const prompt=`You are PlateScan AI for cafeteria food-waste research. Analyze ONLY what is visually supported. Do not hallucinate. Recognize specific Indian foods when visually supported, including Bhindi Sabzi, Kaddu Sabzi, Gawar Sabzi, Lauki, Tinda, Kohda, Dum Aloo, Aloo Gobi, Baingan Bharta, Karela, Torai, Parwal, Mix Veg, Chole, Rajma, Paneer, Dal, Dal Tadka, Dal Fry, Dal Makhani, Moong Dal, Masoor Dal, Chana Dal, Toor/Arhar Dal, Kadhi, Rice/Chawal, Jeera Rice, Pulao, Biryani, Khichdi, Roti/Chapati, Paratha, Puri, Idli, Dosa, Sambar, Poha, Upma, Curd/Dahi, Salad and Pickle/Achaar. If a specific dish is not distinguishable reliably, use a truthful broader name or omit it. For each visible food report remainingAmount as the best human-readable approximate amount, remainingPercent 0-100 as a visual estimate of the portion remaining compared with the original portion, estimatedCount as an approximate number of countable pieces ONLY when visually supported (for example 2 rotis, 1.5 rotis, 3 puris, 2 idlis), otherwise null, and unit as roti, piece, puri, idli, katori, cup, bowl or similar. You may use fractional counts such as 1.5 rotis when visually supported. For non-countable foods such as rice, dal and sabzi, prefer visible serving estimates such as ~1/2 katori or ~1 cup. Never claim exact grams/ml from an image alone. If exact quantity is impossible, give the closest honest visual estimate and lower confidence. Return ONLY JSON: {"plateDetected":true,"foods":[{"name":"Roti","remainingAmount":"~1.5 rotis","remainingPercent":50,"estimatedCount":1.5,"unit":"roti","confidence":0.9,"emoji":"🫓"}],"note":""}. Omit uncertain foods below confidence 0.45.`;
function parse(s:string){return JSON.parse(s.replace(/```json|```/g,"").trim())}function pct(a:string,p:any){const n=Number(p);if(Number.isFinite(n)&&n>=0&&n<=100)return Math.round(n);const x=a.toLowerCase();if(x.includes("nearly"))return 5;if(x.includes("very small"))return 10;if(x.includes("small"))return 25;if(x.includes("medium"))return 50;if(x.includes("large"))return 75;const m=x.match(/(\d+)\s*\/\s*(\d+)/);return m?Math.round(Number(m[1])/Number(m[2])*100):null}
app.get("/api/hardware/weight/latest",(_q,r)=>{
  if(latestHardwareWeightKg==null) return r.status(503).json({error:"No load-cell reading received from Raspberry Pi yet."});
  r.json({weightKg:latestHardwareWeightKg,receivedAt:latestHardwareAt});
});
app.post("/api/hardware/weight",(q,r)=>{
  const token=String(q.headers["x-pi-device-token"]||q.body?.token||"");
  if(deviceToken() && token!==deviceToken()) return r.status(401).json({error:"Invalid PI_DEVICE_TOKEN"});
  const kg=Number(q.body?.weightKg);
  if(!Number.isFinite(kg)||kg<0) return r.status(400).json({error:"weightKg must be a non-negative number"});
  latestHardwareWeightKg=kg; latestHardwareAt=new Date().toISOString();
  r.json({ok:true,weightKg:kg,receivedAt:latestHardwareAt});
});
app.get("/api/health",(_q,r)=>r.json({ok:true,nabhConfigured:Boolean(process.env.NABH_API_KEY?.trim()),model:process.env.NABH_MODEL||"qwen2-5-vl-72b"}));
app.post("/api/sessions",(q,r)=>{const date=String(q.body.sessionDate||new Date().toISOString().slice(0,10));const day=String(q.body.dayLabel||`Day ${date}`);const meal=String(q.body.mealType||"Lunch");const id=crypto.randomUUID();db.prepare("INSERT INTO sessions(id,session_date,day_label,round_number,session_type,meal_type,started_at) VALUES(?,?,?,?,?,?,?)").run(id,date,day,0,"meal",meal,new Date().toISOString());r.json({id,sessionDate:date,dayLabel:day,mealType:meal})});
app.post("/api/sessions/:id/finish",(q,r)=>{db.prepare("UPDATE sessions SET finished_at=? WHERE id=?").run(new Date().toISOString(),q.params.id);r.json({ok:true})});
app.get("/api/sessions/:id/summary",(q,r)=>{const s=db.prepare("SELECT * FROM sessions WHERE id=?").get(q.params.id);if(!s)return r.status(404).json({error:"Session not found"});const rows=db.prepare(`SELECT p.id,p.sequence,p.captured_at,fo.name,fo.remaining_amount,fo.remaining_percent,fo.estimated_count,fo.unit,fo.confidence,fo.emoji FROM plates p LEFT JOIN food_observations fo ON fo.plate_id=p.id WHERE p.session_id=? ORDER BY p.sequence,fo.id`).all(q.params.id) as any[];const ids=new Set(rows.map(x=>x.id));const left=new Set(rows.filter(x=>Number(x.remaining_percent)>0).map(x=>x.id));const byFood=db.prepare(`SELECT fo.name,COUNT(*) observations,ROUND(AVG(fo.remaining_percent),0) avg_remaining_percent,ROUND(AVG(fo.confidence),3) avg_confidence FROM food_observations fo JOIN plates p ON p.id=fo.plate_id WHERE p.session_id=? GROUP BY fo.name ORDER BY observations DESC`).all(q.params.id);const targets=db.prepare("SELECT * FROM food_targets WHERE session_id=? ORDER BY id").all(q.params.id);const ps=rows.map(x=>Number(x.remaining_percent)).filter(Number.isFinite);r.json({session:s,totalPlates:ids.size,leftoverPlates:left.size,percentPlatesWithAnyLeftover:ids.size?Math.round(left.size/ids.size*100):0,avgObservedPercent:ps.length?Math.round(ps.reduce((a,b)=>a+b,0)/ps.length):null,byFood,targets,plates:rows})});
app.get("/api/history",(_q,r)=>{const sessions=db.prepare(`SELECT s.*,COUNT(DISTINCT p.id) plate_count,COUNT(DISTINCT CASE WHEN fo.remaining_percent>0 THEN p.id END) plates_with_leftovers FROM sessions s LEFT JOIN plates p ON p.session_id=s.id LEFT JOIN food_observations fo ON fo.plate_id=p.id GROUP BY s.id ORDER BY s.session_date DESC,s.round_number ASC`).all();const days=db.prepare(`SELECT s.session_date,MAX(s.day_label) day_label,COUNT(DISTINCT s.id) meals,COUNT(DISTINCT p.id) plates,COUNT(DISTINCT CASE WHEN fo.remaining_percent>0 THEN p.id END) leftover_plates,ROUND(AVG(fo.remaining_percent),0) avg_remaining_percent FROM sessions s LEFT JOIN plates p ON p.session_id=s.id LEFT JOIN food_observations fo ON fo.plate_id=p.id GROUP BY s.session_date ORDER BY s.session_date DESC`).all();r.json({sessions,days})});
app.get("/api/days/:date",(q,r)=>{const date=q.params.date;const sessions=db.prepare(`SELECT s.*,COUNT(DISTINCT p.id) plate_count,COUNT(DISTINCT CASE WHEN fo.remaining_percent>0 THEN p.id END) plates_with_leftovers FROM sessions s LEFT JOIN plates p ON p.session_id=s.id LEFT JOIN food_observations fo ON fo.plate_id=p.id WHERE s.session_date=? GROUP BY s.id ORDER BY s.round_number`).all(date);const food=db.prepare(`SELECT fo.name,COUNT(*) observations,ROUND(AVG(fo.remaining_percent),0) avg_remaining_percent,ROUND(SUM(COALESCE(fo.remaining_percent,0)),0) sum_remaining_percent FROM food_observations fo JOIN plates p ON p.id=fo.plate_id JOIN sessions s ON s.id=p.session_id WHERE s.session_date=? GROUP BY fo.name ORDER BY observations DESC`).all(date);const total=(db.prepare("SELECT COUNT(DISTINCT p.id) n FROM plates p JOIN sessions s ON s.id=p.session_id WHERE s.session_date=?").get(date) as {n:number}).n;const left=(db.prepare("SELECT COUNT(DISTINCT p.id) n FROM plates p JOIN sessions s ON s.id=p.session_id JOIN food_observations fo ON fo.plate_id=p.id WHERE s.session_date=? AND fo.remaining_percent>0").get(date) as {n:number}).n;r.json({date,sessions,food,totalPlates:total,leftoverPlates:left,percentPlatesWithAnyLeftover:total?Math.round(left/total*100):0})});
app.get("/api/sessions/:id/export",(q,r)=>{const summary=(db.prepare("SELECT * FROM sessions WHERE id=?").get(q.params.id));const plates=db.prepare(`SELECT p.sequence,p.captured_at,fo.name,fo.remaining_amount,fo.remaining_percent,fo.estimated_count,fo.unit,fo.confidence,fo.emoji FROM plates p LEFT JOIN food_observations fo ON fo.plate_id=p.id WHERE p.session_id=? ORDER BY p.sequence,fo.id`).all(q.params.id);const targets=db.prepare("SELECT * FROM food_targets WHERE session_id=?").all(q.params.id);r.json({session:summary,targets,plates})});
app.post("/api/analyze-food",upload.single("image"),async(q,r)=>{if(!q.file)return r.status(400).json({error:"Image is required"});if(!process.env.NABH_API_KEY)return r.status(500).json({error:"NABH_API_KEY is missing in backend/.env"});try{const b=q.file.buffer.toString("base64"),mime=q.file.mimetype||"image/jpeg";const out=await getClient().chat.completions.create({model:process.env.NABH_MODEL||"qwen2-5-vl-72b",temperature:.1,max_tokens:1000,messages:[{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:`data:${mime};base64,${b}`}}]}]});const raw=out.choices[0]?.message?.content;if(typeof raw!=="string")throw new Error("Vision model returned no text");const x=parse(raw);const foods=Array.isArray(x.foods)?x.foods.filter((f:any)=>Number(f.confidence)>=.45).map((f:any)=>({name:String(f.name),remainingAmount:String(f.remainingAmount),remainingPercent:pct(String(f.remainingAmount),f.remainingPercent),estimatedCount:f.estimatedCount==null?null:Number(f.estimatedCount),unit:String(f.unit||""),confidence:Number(f.confidence),emoji:String(f.emoji||"🍽️")})):[];const result:any={plateDetected:Boolean(x.plateDetected),foods,note:x.note||""};const sid=typeof q.body.sessionId==="string"?q.body.sessionId:"";if(sid&&result.plateDetected&&db.prepare("SELECT id FROM sessions WHERE id=?").get(sid)){const save= db.transaction(()=>{const n=db.prepare("SELECT COALESCE(MAX(sequence),0)+1 n FROM plates WHERE session_id=?").get(sid) as {n:number};const pid=crypto.randomUUID(),at=new Date().toISOString();db.prepare("INSERT INTO plates(id,session_id,sequence,captured_at,image_name) VALUES(?,?,?,?,?)").run(pid,sid,n.n,at,q.file.originalname);const ins=db.prepare("INSERT INTO food_observations(plate_id,name,remaining_amount,remaining_percent,estimated_count,unit,confidence,emoji) VALUES(?,?,?,?,?,?,?,?)");for(const f of foods)ins.run(pid,f.name,f.remainingAmount,f.remainingPercent,f.estimatedCount,f.unit,f.confidence,f.emoji);return {sequence:n.n,captured_at:at,foods}});result.plate=save()}r.json(result)}catch(e){console.error(e);r.status(500).json({error:e instanceof Error?e.message:"AI analysis failed"})}});
app.listen(port,"0.0.0.0",()=>console.log(`PlateScan backend listening on http://localhost:${port}`));